variables:
  __GIT_SUBMODULE__: _____________________________________________________
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

  __DOCKER_________: _____________________________________________________
  GET_DOCKER_URL: $CI_CD_GLOBAL_GET_DOCKER_URL

  __IMAGE_TAGS_____: _____________________________________________________
  DEBIAN_IMAGE_TAG: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/$CI_CD_GLOBAL_DOCKER_IMAGE_TAG_DEBIAN
  DOCKER_IMAGE_TAG: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/$CI_CD_GLOBAL_DOCKER_IMAGE_TAG_DOCKER
  GRADLE_IMAGE_TAG: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/$CI_CD_GLOBAL_DOCKER_IMAGE_TAG_GRADLE
  NODE_IMAGE_TAG: $CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX/$CI_CD_GLOBAL_DOCKER_IMAGE_TAG_NODE
