.gradle-config:
  script:
    - projectVersion=$(gradle -q printProjectVersion)

.gradle-check:
  script:
    - gradle check -x test -x build --refresh-dependencies --warning-mode all --info

.gradle-sonar:
  script:
    - gradle sonar --refresh-dependencies --warning-mode all --info

.gradle-build:
  script:
    - gradle build -x check -x test --refresh-dependencies --warning-mode all --info

.gradle-test:
  script:
    - gradle test -x check -x build --refresh-dependencies --warning-mode all --info

.gradle-javadoc:
  script:
    - gradle javadoc -x check -x test -x build --refresh-dependencies --warning-mode all --info

.gradle-changelog:
  script:
    - gradle changelog --refresh-dependencies --warning-mode all --info

.gradle-cleanDist:
  script:
    - gradle cleanDist --refresh-dependencies --warning-mode all --info

.gradle-makeDist:
  script:
    - gradle makeDist --refresh-dependencies --warning-mode all --info
