#!/bin/sh

GIT_USER=lild
GIT_EMAIL=lildworks@gmail.com

main() {
    log "DEBUG" "code-server -- post-install..."

    cmds="upgradeCodeServer installGit installGitFlow installDockerEngine installDockerCompose"
    for cmd in $cmds; do
        log "DEBUG" "code-server -- -- run cmd: '$cmd'"
        eval $cmd
    done
}

log() {
    logLevel=$1
    logMessage=$2

    now=$(date +"%Y-%m-%d %H:%M:%S.%3N")

    printf "$now [$logLevel] %s\n" "$logMessage"
}

upgradeCodeServer() {
    me=$(whoami)

    sudo apt update
    sudo apt upgrade -y
    sudo apt install -y build-essential net-tools curl htop mc nano

    sudo chown -Rv $me:$me /config/
    sudo chown -Rv $me:$me /works/

    sudo apt autoremove -y
}

installGit() {
    gitUser=$GIT_USER
    gitEmail=$GIT_EMAIL

    sudo apt update
    sudo apt install -y git

    git config --global user.name $gitUser
    git config --global user.email $gitEmail
    git config --global credential.helper "cache --timeout=-1"
    git config --global init.defaultBranch master

    sudo apt autoremove -y
}

installGitFlow() {
    sudo apt update
    sudo apt install -y git-flow
    sudo apt autoremove -y
}

installDockerEngine() {
    me=$(whoami)

    curl -sL "https://get.docker.com" | /bin/sh

    sudo adduser $me sudo
    sudo adduser $me docker

    sudo apt autoremove -y
}

installDockerCompose() {
    sudo apt update
    sudo apt-get install -y docker-compose
    sudo apt autoremove -y
}

main
