networks:
  nginx:
    name: nginx-net
services:
  nginx:
    image: jc21/nginx-proxy-manager:{{ NGINX_PROXY_MANAGER__IMAGE_TAG }}
    container_name: nginx
    restart: unless-stopped
    volumes:
      - /srv/nginx/data:/data
      - /srv/nginx/letsencrypt:/etc/letsencrypt
    networks:
      - nginx-net
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:81:81
