networks:
  portainer:
    name: portainer
  nginx:
    name: nginx
services:
  portainer:
    image: portainer/portainer-ee:2.21.2-alpine
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /srv/portainer/data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - portainer
    ports:
      - 127.0.0.1:9000:9000
  nginx:
    image: jc21/nginx-proxy-manager:2.12.1
    container_name: nginx
    restart: unless-stopped
    volumes:
      - /srv/nginx/data:/data
      - /srv/nginx/letsencrypt:/etcc/letsencrypt
    networks:
      - nginx
    ports:
      - 80:80
      - 443:443
      - 127.0.0.1:81:81
